/* Generated By:JavaCC: Do not edit this line. compilerTreeConstants.java Version 5.0 */
package Interpreter;

public interface compilerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROCEDURE = 1;
  public int JJTSTATEMENT = 2;
  public int JJTVARIALBEDECLARATION = 3;
  public int JJTBLOCK = 4;
  public int JJTEXPRESSION = 5;
  public int JJTTERM = 6;
  public int JJTFACTOR = 7;
  public int JJTCONDITION = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTINTEGER = 10;
  public int JJTREAL = 11;
  public int JJTBOOL = 12;


  public String[] jjtNodeName = {
    "Start",
    "Procedure",
    "Statement",
    "VarialbeDeclaration",
    "Block",
    "Expression",
    "Term",
    "Factor",
    "Condition",
    "Identifier",
    "Integer",
    "Real",
    "Bool",
  };
}
/* JavaCC - OriginalChecksum=0ecd58b73fdb95923fdf4c93e7a62ab3 (do not edit this line) */
